### ISSUE TITLE
v9.6 website slow response

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3843]
Hi Daniel,

I feel after update to the v9.6
The website quite slow response when compare with the v9.5

So, I tryout goto see the log.
I found so many line warning below.

[17-Oct-2020 16:55:29 Asia/Krasnoyarsk] PHP Warning:  array_merge(): Argument #2 is not an array in path/to/my/streamer/site/plugin/AVideoPlugin.php on line 707

I'm not sure this is the cause or not.

**Comment by DanielnetoDotCom** [comment]
please make sure you have the update from yesterday night. 

I have fixed a lot of warnings

**Comment by guitarpound** [comment]
Hi,

I just update it today before this post 2 hours ago.

**Comment by DanielnetoDotCom** [comment]
I cannot see any reason to slow it down, try to check your logs.

**Comment by JoshWho** [comment]
Delete the PHP Memory Limit in your .htaccess file of the root of your web directory.

**Comment by guitarpound** [comment]
Hi @DanielnetoDotCom & @JoshWho 

I try update to the latest version again today the problem still there.

here are video speed test Before & After update from v9.5 to v9.7
(you will see the loading on favicon at Browser tab)

v9.5
https://drive.google.com/file/d/1cCSPFtgtL2DLfwj0B1W6XNvZ53qohtdp/view?usp=sharing

v9.7 
https://drive.google.com/file/d/17lOiriviAVTGJYyp2KzIuL8byqXbM6cL/view?usp=sharing

**Comment by JoshWho** [comment]
Did u delete  the memory limit?

**Comment by guitarpound** [comment]
Yes, In the v9.7 don't have memory limit in .htaccess anymore.

**Comment by JoshWho** [comment]
Weird, that was the only thing causing me issues. Everything went to normal after that.

**Comment by DanielnetoDotCom** [comment]
@guitarpound please check the log for some clue.

there is any specific page that is slow?

**Comment by guitarpound** [comment]
@DanielnetoDotCom 

I found after login.  All the link in web pages slow response and I just found Live button not response. I have to restart apache to get the system back.
If no login the web pages fast normally.

So, I tried deleting the avideo.log files and then try clicking each menu step by step to find out which link clicked that caused error in the log file.

I found when clicked Users Menu
It will show 49 PHP warning in one time on the Log file.
I selected only unique errors line to show you below.

[28-Oct-2020 22:42:20 Asia/Krasnoyarsk] PHP Warning:  Invalid argument supplied for foreach() in path/to/my/streamer/site/plugin/AVideoPlugin.php on line 762
..
[28-Oct-2020 22:42:20 Asia/Krasnoyarsk] PHP Warning:  array_merge(): Argument #1 is not an array in path/to/my/streamer/site/plugin/AVideoPlugin.php on line 707
..
.. ( many repeat of plugin/AVideoPlugin.php on line 707 )
.. 
[28-Oct-2020 22:42:20 Asia/Krasnoyarsk] PHP Notice:  Undefined variable: userOptions in path/to/my/streamer/site/plugin/CustomizeUser/CustomizeUser.php on line 149
..
[28-Oct-2020 22:42:20 Asia/Krasnoyarsk] PHP Warning:  Invalid argument supplied for foreach() in path/to/my/streamer/site/plugin/AVideoPlugin.php on line 771
..
[28-Oct-2020 22:42:20 Asia/Krasnoyarsk] PHP Warning:  Invalid argument supplied for foreach() in path/to/my/streamer/site/plugin/AVideoPlugin.php on line 736
