### ISSUE TITLE
CustomizeAdvanced and showImageDownloadOption

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3980]
The option does not work, even if it is not selected, some images and HLS files are displayed for download.

![image](https://user-images.githubusercontent.com/52116237/98469657-32e29380-21e1-11eb-8970-b26b0cad76c0.png)

**Comment by DanielnetoDotCom** [comment]
Hi

can you please screenshot where did you see the "displayed for download"?

**Comment by Donnerstein** [comment]
The error occurred after an update from version 8.9 to the latest. I cannot test on the demo page. If I activate the download option in the CustomizeAdvanced plugin on the demo page. If there is an error 500

![image](https://user-images.githubusercontent.com/52116237/98648265-566b2280-2336-11eb-9cac-3b83ce97207c.png)


![image](https://user-images.githubusercontent.com/52116237/98648284-5f5bf400-2336-11eb-9408-62b144c72a3f.png)

![image](https://user-images.githubusercontent.com/52116237/98648327-6d117980-2336-11eb-9268-1622c128cca4.png)

**Comment by DanielnetoDotCom** [comment]
thanks, Demo page is fixed now

thanks for noticing the wrong download menu, here is a fix

**Comment by Donnerstein** [comment]
Yes, only that there is no longer a distinction between SD, Low and HD

![image](https://user-images.githubusercontent.com/52116237/98684419-6f8bc780-2366-11eb-86fe-87e4e3cb42ec.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, try this new update

**Comment by Donnerstein** [comment]
Many thanks.

![image](https://user-images.githubusercontent.com/52116237/98687644-3f462800-236a-11eb-9a58-206c14e39402.png)

**Comment by Donnerstein** [comment]
I'm sorry to have to reopen the topic, but today I saw that you forgot the entries in the right-click menu.

![image](https://user-images.githubusercontent.com/52116237/98850512-2c5c5200-2455-11eb-8db5-d193421f6d74.png)

**Comment by DanielnetoDotCom** [comment]
Try this please.

**Comment by Donnerstein** [comment]
Thank you
