### ISSUE TITLE
YouPHPFlix2 Plugin does not support displaying of categories.

### ISSUE THREAD

**Issue by iVrata** [WWBN/AVideo#4325]
**Describe the bug**
When you use the check box to show categories of content, it shows text at the bottom of the first page.

**To Reproduce**
1. Go to plugins, go to YouPHPFlix2 and click on Edit Parameters
2. Scroll down to "show categories" and click on check box
3. See error on first page.  Please clear cache on first page and see at the bottom of the page

**Expected behavior**
Expect to see the list of categories and a list of shows associated with those categories.  In version 8.8 it worked fine, upgraded to 10.0 and now it is broken.

**Error Logs**
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/portal\/objects\/mysql_dal.php","line":134,"function":"log_error","args":["[sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'Video.livelinks' doesn't exist (SELECT * FROM categories c WHERE 1=1  AND ((SELECT count(*) FROM videos v where v.categories_id = c.id OR categories_id IN (SELECT id from categories where parentId = c.id)) > 0   OR  ( SELECT count(*) FROM live_transmitions lt where  (lt.categories_id = c.id OR lt.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0   OR  ( SELECT count(*) FROM livelinks ll where  (ll.categories_id = c.id OR ll.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0  ) ORDER BY `order`, name ASC  LIMIT 0, 2 ) - format=() values=[]"]},{"file":"\/var\/www\/portal\/objects\/category.php","line":402,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT * FROM categories c WHERE 1=1  AND ((SELECT count(*) FROM videos v where v.categories_id = c.id OR categories_id IN (SELECT id from categories where parentId = c.id)) > 0   OR  ( SELECT count(*) FROM live_transmitions lt where  (lt.categories_id = c.id OR lt.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0   OR  ( SELECT count(*) FROM livelinks ll where  (ll.categories_id = c.id OR ll.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0  ) ORDER BY `order`, name ASC  LIMIT 0, 2 "]},{"file":"\/var\/www\/portal\/plugin\/YouPHPFlix2\/view\/modeFlixCategory.php","line":62,"function":"getAllCategories","class":"Category","type":"::","args":[false,true]}] SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'Video.livelinks' doesn't exist (SELECT * FROM categories c WHERE 1=1  AND ((SELECT count(*) FROM videos v where v.categories_id = c.id OR categories_id IN (SELECT id from categories where parentId = c.id)) > 0   OR  ( SELECT count(*) FROM live_transmitions lt where  (lt.categories_id = c.id OR lt.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0   OR  ( SELECT count(*) FROM livelinks ll where  (ll.categories_id = c.id OR ll.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0  ) ORDER BY `order`, name ASC  LIMIT 0, 2 ) - format=() values=[] SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/portal\/objects\/mysql_dal.php","line":135,"function":"log_error","args":["[sqlDAL::readSql] trying close and reconnect"]},{"file":"\/var\/www\/portal\/objects\/category.php","line":402,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT * FROM categories c WHERE 1=1  AND ((SELECT count(*) FROM videos v where v.categories_id = c.id OR categories_id IN (SELECT id from categories where parentId = c.id)) > 0   OR  ( SELECT count(*) FROM live_transmitions lt where  (lt.categories_id = c.id OR lt.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0   OR  ( SELECT count(*) FROM livelinks ll where  (ll.categories_id = c.id OR ll.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0  ) ORDER BY `order`, name ASC  LIMIT 0, 2 "]},{"file":"\/var\/www\/portal\/plugin\/YouPHPFlix2\/view\/modeFlixCategory.php","line":62,"function":"getAllCategories","class":"Category","type":"::","args":[false,true]}] SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: [sqlDAL::readSql] trying close and reconnect SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/portal\/objects\/mysql_dal.php","line":139,"function":"log_error","args":["[sqlDAL::readSql] (mysqlnd) Prepare failed again return false"]},{"file":"\/var\/www\/portal\/objects\/category.php","line":402,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT * FROM categories c WHERE 1=1  AND ((SELECT count(*) FROM videos v where v.categories_id = c.id OR categories_id IN (SELECT id from categories where parentId = c.id)) > 0   OR  ( SELECT count(*) FROM live_transmitions lt where  (lt.categories_id = c.id OR lt.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0   OR  ( SELECT count(*) FROM livelinks ll where  (ll.categories_id = c.id OR ll.categories_id IN (SELECT id from categories where parentId = c.id)) ) > 0  ) ORDER BY `order`, name ASC  LIMIT 0, 2 "]},{"file":"\/var\/www\/portal\/plugin\/YouPHPFlix2\/view\/modeFlixCategory.php","line":62,"function":"getAllCategories","class":"Category","type":"::","args":[false,true]}] SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:35 Africa/Abidjan] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
[08-Jan-2021 18:40:51 Africa/Abidjan] AVideoLog::DEBUG: Live::getStatsObject RTMP Server (https://video.americonictv.com:8443/stat) is NOT responding we will wait less from now on => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php

**Screenshots**

See below

**Desktop (please complete the following information):**
Chrome browser, MSEdge, Safari

**Smartphone (please complete the following information):**
Shows up on all phones tested regardless of browser

![2021-01-08_12-45-35](https://user-images.githubusercontent.com/61752017/104052530-7b053e80-51af-11eb-8a94-2d921e14599a.png)

**Comment by akhilleusuggo** [comment]
update your code 
( this issue was fixed yesterday )

**Comment by iVrata** [comment]
I updated to 10.0 and it was then that it showed up.  Are you saying their is another YouPHPFlix2 plugin update?

**Comment by DanielnetoDotCom** [comment]
Hi, I found the problem, please update again,

Looks like in some MySQL the table names are case sensitive 

Now you have an update button

![image](https://user-images.githubusercontent.com/18009293/104063774-76ef1600-51db-11eb-94f3-8ac65242be54.png)

**Comment by syldri** [comment]
hello @DanielnetoDotCom 
following the update I still have this bug my demo site

![image](https://user-images.githubusercontent.com/39193219/104075393-f21fee80-5212-11eb-8b75-5d79e9de323d.png)

**Comment by DanielnetoDotCom** [comment]
Then click on the Update to 3.1 button

**Comment by syldri** [comment]
I have already updated everything

![image](https://user-images.githubusercontent.com/39193219/104077203-0961da80-5219-11eb-867f-dc006d00e2bb.png)


![image](https://user-images.githubusercontent.com/39193219/104077220-1da5d780-5219-11eb-8eee-46828b7515e6.png)

**Comment by DanielnetoDotCom** [comment]
Please run this manually https://github.com/WWBN/AVideo/blob/master/plugin/LiveLinks/install/updateV3.0.sql

**Comment by syldri** [comment]
hello @DanielnetoDotCom  the problem continues with the subcategories

![image](https://user-images.githubusercontent.com/39193219/104110452-198cbf00-52d8-11eb-83f0-6eb9b620905f.png)

**Comment by DanielnetoDotCom** [comment]
Sorry I guess I found the problem

**Comment by syldri** [comment]
I did a new installation of the site

I test the table

![image](https://user-images.githubusercontent.com/39193219/104111616-30391300-52e4-11eb-9b23-312187381396.png)

**Comment by syldri** [comment]
I just updated the error has disappeared
