### ISSUE TITLE
Is this the new symbol for connected web socket

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5037]
Was the green connected logo replaced by blue spinning logo? Or does this indicate a problem?

![20210429_023412](https://user-images.githubusercontent.com/70327833/116523618-a8c3df80-a893-11eb-9b2b-90cd2cbfa2f8.jpg)

**Comment by DanielnetoDotCom** [comment]
This should fix it

**Comment by morbificagent** [comment]
![Unbenannt.PNG](https://user-images.githubusercontent.com/50199132/116623046-ef721200-a945-11eb-8244-e69ac0107f82.PNG)

And my Socket doesnt want to connect anymore...

Git pull from some minutes ago, restartet the server.php from the socket, test.php gives "success" and cleared all caches

**Comment by milehighkaraoke** [comment]
Morbificagent,  did this just happen today after a gitpull? If so I'm not updating today

**Comment by morbificagent** [comment]
Yes but i havent pulled a few days now so i cabt say when the change was made that gave me this fun

**Comment by milehighkaraoke** [comment]
Pull today. That fun was fixed in newest commits

**Comment by milehighkaraoke** [comment]
![Uploading 20210429_163853.jpg…]()

**Comment by milehighkaraoke** [comment]
![20210429_163853](https://user-images.githubusercontent.com/70327833/116639908-d0b05300-a926-11eb-9c97-faeeefab639f.jpg)

**Comment by morbificagent** [comment]
![Screenshot_20210430-062919_Chrome.jpg](https://user-images.githubusercontent.com/50199132/116648491-768eac80-a97d-11eb-889b-4cc569014603.jpg)

The update to 10.8 was displayed here too and was running successful but the yptsocket problem remains

**Comment by morbificagent** [comment]
But like you can see on my first screenshot im not sure if its only a display problem and its connected internaly well or not... It responds, it shows connnction messages but then this "onuserconnectionerror"

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom do you have any ideas on this?

**Comment by morbificagent** [comment]
OK, solved this for me... After the git pull i had to purge my CDN-Cache too... Now its connecting well

**Comment by milehighkaraoke** [comment]
Good deal
