### ISSUE TITLE
Video size does not match actual size

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5552]
The original size of the video is more than 30MB. The display size below does not match the actual size of the video. This will not work well with the (DiskUploadQuota) plug-in.
![image](https://user-images.githubusercontent.com/47063171/129324989-b6a6f3a8-9984-4108-a531-60c71bfbcec7.png)

**Comment by milehighkaraoke** [comment]
have you updated your encoder site to latest version?

**Comment by chenjian9885** [comment]
I am testing at the demo station (https://demo.avideo.com/), the video format is m3u8

**Comment by milehighkaraoke** [comment]
Ok, not sure. I am running latest on my own box and not able to replicate

**Comment by chenjian9885** [comment]
The same video, m3u8 format video cannot obtain the actual occupied space
![image](https://user-images.githubusercontent.com/47063171/129337981-29791314-33d5-4222-b949-797f343f5189.png)

**Comment by chenjian9885** [comment]
Caused me to be unable to use the DiskUploadQuota plugin

**Comment by DanielnetoDotCom** [comment]
If you log in as admin and click to update the disk usage does it get the correct value?

![image](https://user-images.githubusercontent.com/18009293/129356385-d5b4fb0d-8a6b-417f-9492-a25a5e78b89c.png)

**Comment by chenjian9885** [comment]
I have tried it, but to no avail.






------------------ Original ------------------
From: Daniel Neto ***@***.***&gt;
Date: Fri,Aug 13,2021 8:22 PM
To: WWBN/AVideo ***@***.***&gt;
Cc: chenjian9885 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [WWBN/AVideo] Video size does not match actual size (#5552)





 
If you log in as admin and click to update the disk usage does it get the correct value?
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DanielnetoDotCom** [comment]
What do you mean it is not available?

if you are admin it must be available

**Comment by chenjian9885** [comment]
Sorry maybe I can’t describe clearly
I saw the error on (demo.avideo.com). My login account is: admin and password is: 123. I found that the size of the m3u8 format video is quite different from the size of the occupied disk.

**Comment by chenjian9885** [comment]
Is the size of these videos actually the size of the disk?
![image](https://user-images.githubusercontent.com/47063171/129393022-0d399803-1ace-4ee8-9e94-e6c6e3f5da9f.png)
![image](https://user-images.githubusercontent.com/47063171/129393223-faa922c6-d7cf-44a0-bccc-65f7e7956a02.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that. 

This issue may be resolved with the last update.

**Comment by chenjian9885** [comment]
Hope to update as soon as possible, DiskUploadQuota plug-in is great, hope to use it as soon as possible.

**Comment by milehighkaraoke** [comment]
Do a gitpull on your site folder

**Comment by DanielnetoDotCom** [comment]
> Hope to update as soon as possible, DiskUploadQuota plug-in is great, hope to use it as soon as possible.

Check this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by chenjian9885** [comment]
Thanks! awesome.

**Comment by chenjian9885** [comment]
terribly sorry! I have to reopen this topic again. The real size of the video can only be obtained when the storage location is local, and the real size of the video cannot be obtained from other branch storage.
![image](https://user-images.githubusercontent.com/47063171/129701554-2c5dddd2-b8d3-4966-928a-8a7ba56da849.png)
![image](https://user-images.githubusercontent.com/47063171/129701663-e6fd95d7-7c9b-4f73-a70f-e7e0be3f4056.png)

**Comment by DanielnetoDotCom** [comment]
Hi

what type of storage are you using?

**Comment by chenjian9885** [comment]
Hello
I plan to use your DiskUploadQuota plug-in and YPTWallet plug-in, so I used your demo site (demo.avideo.com) to test, and I tested the YPTWallet plug-in storage
![image](https://user-images.githubusercontent.com/47063171/129748959-2eeca347-4f20-4663-aeab-375445bf35ed.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, I guess it is fixed now.

To be honest I am not sure if the issue was on the YPTStorage server or plugin, but to get away from this issue I recommend you to update both.

**Comment by chenjian9885** [comment]
I haven’t seen any changes on the demo site (demo.avideo.com)?
![image](https://user-images.githubusercontent.com/47063171/129843446-7078bf7f-287e-4471-b348-c54f15d8f619.png)

**Comment by DanielnetoDotCom** [comment]
Click on the Update disk usage on demo site.

**Comment by chenjian9885** [comment]
I have clicked to update the disk usage on the demo site, and there is still no change.
![image](https://user-images.githubusercontent.com/47063171/129954743-e24ac36c-64d8-4ffb-a9a3-77c4586711af.png)

**Comment by DanielnetoDotCom** [comment]
Hi, thanks I found the issue , it was something only for a HLS video, it seems to be fine now

**Comment by chenjian9885** [comment]
awesome! It works well now.
