### ISSUE TITLE
encoder import function now broken

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7682]
Hi,

The import function on the encoder doesnt work now. Same problem on 2 servers and a fresh install for testing.  it was working perfectly before.

Array
(
    [0] => ERROR: [youtube] jJZjD3S-dlI: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
)

**Comment by DanielnetoDotCom** [comment]
this is a recent error on yt-dlp

there is a workaround 

try this 

```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```

**Comment by para2022** [comment]
That fixed it. Thanks mate your a star.

**Comment by JoshWho** [comment]
ERROR: Package 'yt-dlp' requires a different Python: 3.6.9 not in '>=3.7'
root@mail3:~#

**Comment by JoshWho** [comment]
@DanielnetoDotCom I need your help with this. I do not see why it is not letting me upgrade this so the dlp can work. 

```
ERROR: Package 'yt-dlp' requires a different Python: 3.6.9 not in '>=3.7'
root@mail3:~#
```

**Comment by JoshWho** [comment]
I installed the 3.7 and that didn't seem to change anything

**Comment by JoshWho** [comment]
Nevermind I got it solved now. It was a broken package I reinstalled now workd fine

**Comment by vraghavans** [comment]
hi @JoshWho ERROR: Package 'yt-dlp' requires a different Python: 3.6.9 not in '>=3.7'
root@mail3:~#

Am also getting this error,can you guide me what you did please

**Comment by DanielnetoDotCom** [comment]
try this 

Update your system's package manager to ensure that you have the latest version of available packages. You can do this by running the following command in a terminal:

`sudo apt update`

Upgrade your system's Python version to a version that is compatible with the "yt-dlp" package. Ubuntu 18 comes with Python 3.6.9 by default, which is not compatible with the package. You can install a newer version of Python using the deadsnakes PPA:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.8
```

**Comment by vraghavans** [comment]
Hi Daniel,

Still the same error please

![image](https://user-images.githubusercontent.com/65802024/222271228-923ef5a1-a909-4883-af83-797a8ee7ce9d.png)
Please help!

**Comment by DanielnetoDotCom** [comment]
I apologize, but the issue you are facing does not pertain to AVideo; it is related to a third-party tool. Unfortunately, I am unable to provide guidance on the installation of libraries.

However, there are several guides available on Google that can assist you with the installation process. Alternatively, you may wish to hire me or someone else for direct support.
